"""empty message

Revision ID: 0fa1ed649494
Revises: 2044ce9e16eb
Create Date: 2023-10-16 20:23:04.233333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa1ed649494'
down_revision = '2044ce9e16eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statistics_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_performance_work', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_statistics_user_id_performance_work_performance_work'), 'performance_work', ['id_performance_work'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statistics_user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_statistics_user_id_performance_work_performance_work'), type_='foreignkey')
        batch_op.drop_column('id_performance_work')

    # ### end Alembic commands ###
