"""empty message

Revision ID: 1ab0ad37c11e
Revises: 0fa1ed649494
Create Date: 2023-10-19 22:23:33.939294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab0ad37c11e'
down_revision = '0fa1ed649494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s_p', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transit', schema=None) as batch_op:
        batch_op.drop_column('s_p')

    # ### end Alembic commands ###
