"""empty message

Revision ID: 1ef6b2321964
Revises: 64108b4876d5
Create Date: 2023-03-05 23:25:19.809082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef6b2321964'
down_revision = '64108b4876d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_client_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_upload_file_order_client_id_order_client'), 'order_client', ['order_client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_upload_file_order_client_id_order_client'), type_='foreignkey')
        batch_op.drop_column('order_client_id')

    # ### end Alembic commands ###
