"""empty message

Revision ID: 2044ce9e16eb
Revises: a2cfaf823aa8
Create Date: 2023-10-14 00:16:52.265579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2044ce9e16eb'
down_revision = 'a2cfaf823aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statistics_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('factor_price', sa.REAL(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statistics_user', schema=None) as batch_op:
        batch_op.drop_column('factor_price')

    # ### end Alembic commands ###
