"""empty message

Revision ID: 64108b4876d5
Revises: f1d98f7477d6
Create Date: 2023-03-03 15:52:45.533306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64108b4876d5'
down_revision = 'f1d98f7477d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('upload_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_file', sa.BLOB(), nullable=True))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
