"""empty message

Revision ID: 7554fb5cf5f8
Revises: c734ba5064ec
Create Date: 2023-03-08 14:56:18.717462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7554fb5cf5f8'
down_revision = 'c734ba5064ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_start', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status_pause', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pause_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status_end', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lead_time', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_work', schema=None) as batch_op:
        batch_op.drop_column('lead_time')
        batch_op.drop_column('end_date')
        batch_op.drop_column('status_end')
        batch_op.drop_column('pause_date')
        batch_op.drop_column('status_pause')
        batch_op.drop_column('start_date')
        batch_op.drop_column('status_start')

    # ### end Alembic commands ###
