"""empty message

Revision ID: 7f85657afbc8
Revises: b6ff75bb73f7
Create Date: 2022-12-18 21:52:51.814619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f85657afbc8'
down_revision = 'b6ff75bb73f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_client', 'measurements',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('order_client', 'project_drawing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('order_client', 'control',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_client', 'control',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('order_client', 'project_drawing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('order_client', 'measurements',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
