"""empty message

Revision ID: af582015d81b
Revises: f4b808c0f345
Create Date: 2023-01-29 23:27:04.724063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af582015d81b'
down_revision = 'f4b808c0f345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_user_specialization_id_specialization'), 'specialization', ['specialization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_specialization_id_specialization'), type_='foreignkey')
        batch_op.drop_column('specialization_id')

    # ### end Alembic commands ###
