"""empty message

Revision ID: b42baf10d9bf
Revises: 1ab0ad37c11e
Create Date: 2023-10-19 22:41:25.263274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42baf10d9bf'
down_revision = '1ab0ad37c11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transit', schema=None) as batch_op:
        batch_op.drop_column('s_p')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s_p', sa.VARCHAR(length=5), nullable=True))

    # ### end Alembic commands ###
