"""empty message

Revision ID: b6ff75bb73f7
Revises: 
Create Date: 2022-12-14 12:00:33.507918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ff75bb73f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('phone_number', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_first_name'), 'clients', ['first_name'], unique=False)
    op.create_index(op.f('ix_clients_last_name'), 'clients', ['last_name'], unique=False)
    op.create_index(op.f('ix_clients_phone_number'), 'clients', ['phone_number'], unique=True)
    op.create_table('specialization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_departmet', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialization_job_departmet'), 'specialization', ['job_departmet'], unique=False)
    op.create_index(op.f('ix_specialization_job_title'), 'specialization', ['job_title'], unique=True)
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('works_title', sa.String(length=150), nullable=True),
    sa.Column('works_type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_order', sa.String(length=300), nullable=True),
    sa.Column('title_stone', sa.String(length=300), nullable=True),
    sa.Column('object_description', sa.String(length=2000), nullable=True),
    sa.Column('address', sa.String(length=5000), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('measurements', sa.Boolean(), nullable=False),
    sa.Column('project_drawing', sa.Boolean(), nullable=False),
    sa.Column('control', sa.Boolean(), nullable=False),
    sa.Column('clients_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clients_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('specialization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['specialization_id'], ['specialization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('order_manufacture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raskroj', sa.Boolean(), nullable=False),
    sa.Column('porezka', sa.Boolean(), nullable=False),
    sa.Column('cpu', sa.Boolean(), nullable=False),
    sa.Column('montag', sa.Boolean(), nullable=False),
    sa.Column('vidacha', sa.Boolean(), nullable=False),
    sa.Column('oreder_of_client', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oreder_of_client'], ['order_client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('pre_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_order_client', sa.Integer(), nullable=False),
    sa.Column('work_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['number_order_client'], ['order_client.id'], ),
    sa.ForeignKeyConstraint(['work_type'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_part', sa.String(length=16), nullable=True),
    sa.Column('thickness', sa.String(length=150), nullable=True),
    sa.Column('value', sa.String(length=150), nullable=True),
    sa.Column('deadline_part', sa.DateTime(), nullable=True),
    sa.Column('oreder_of_manufacture', sa.Integer(), nullable=False),
    sa.Column('part_works', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oreder_of_manufacture'], ['order_manufacture.id'], ),
    sa.ForeignKeyConstraint(['part_works'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_works_number_part'), 'part_works', ['number_part'], unique=False)
    op.create_index(op.f('ix_part_works_thickness'), 'part_works', ['thickness'], unique=False)
    op.create_index(op.f('ix_part_works_value'), 'part_works', ['value'], unique=False)
    op.create_table('slab_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_slab', sa.String(length=16), nullable=True),
    sa.Column('thickness', sa.String(length=150), nullable=True),
    sa.Column('value', sa.String(length=150), nullable=True),
    sa.Column('deadline_slab', sa.DateTime(), nullable=True),
    sa.Column('oreder_of_manufacture', sa.Integer(), nullable=False),
    sa.Column('slab_works', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oreder_of_manufacture'], ['order_manufacture.id'], ),
    sa.ForeignKeyConstraint(['slab_works'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slab_works_number_slab'), 'slab_works', ['number_slab'], unique=False)
    op.create_index(op.f('ix_slab_works_thickness'), 'slab_works', ['thickness'], unique=False)
    op.create_index(op.f('ix_slab_works_value'), 'slab_works', ['value'], unique=False)
    op.create_table('performance_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_work_slabs', sa.Integer(), nullable=False),
    sa.Column('connection_work_part', sa.Integer(), nullable=False),
    sa.Column('connection_user', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status_start', sa.Boolean(), nullable=False),
    sa.Column('status_end', sa.Boolean(), nullable=False),
    sa.Column('lead_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connection_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['connection_work_part'], ['part_works.id'], ),
    sa.ForeignKeyConstraint(['connection_work_slabs'], ['slab_works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_work')
    op.drop_index(op.f('ix_slab_works_value'), table_name='slab_works')
    op.drop_index(op.f('ix_slab_works_thickness'), table_name='slab_works')
    op.drop_index(op.f('ix_slab_works_number_slab'), table_name='slab_works')
    op.drop_table('slab_works')
    op.drop_index(op.f('ix_part_works_value'), table_name='part_works')
    op.drop_index(op.f('ix_part_works_thickness'), table_name='part_works')
    op.drop_index(op.f('ix_part_works_number_part'), table_name='part_works')
    op.drop_table('part_works')
    op.drop_table('pre_product')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('order_manufacture')
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_table('user')
    op.drop_table('order_client')
    op.drop_table('works')
    op.drop_index(op.f('ix_specialization_job_title'), table_name='specialization')
    op.drop_index(op.f('ix_specialization_job_departmet'), table_name='specialization')
    op.drop_table('specialization')
    op.drop_index(op.f('ix_clients_phone_number'), table_name='clients')
    op.drop_index(op.f('ix_clients_last_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_first_name'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
