"""empty message

Revision ID: c734ba5064ec
Revises: f1303235051a
Create Date: 2023-03-08 14:55:36.509023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c734ba5064ec'
down_revision = 'f1303235051a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_work', schema=None) as batch_op:
        batch_op.drop_column('lead_time')
        batch_op.drop_column('pause_date')
        batch_op.drop_column('end_date')
        batch_op.drop_column('status_start')
        batch_op.drop_column('start_date')
        batch_op.drop_column('status_pause')
        batch_op.drop_column('status_end')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_end', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('status_pause', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('status_start', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('pause_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('lead_time', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
