"""empty message

Revision ID: ef640376319a
Revises: 0b403357ced1
Create Date: 2022-12-19 13:22:06.778106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef640376319a'
down_revision = '0b403357ced1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_client', 'measurements',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('order_client', 'project_drawing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('order_client', 'control',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_specialization_job_departmet', table_name='specialization')
    op.drop_column('specialization', 'job_departmet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialization', sa.Column('job_departmet', sa.VARCHAR(length=200), nullable=True))
    op.create_index('ix_specialization_job_departmet', 'specialization', ['job_departmet'], unique=False)
    op.alter_column('order_client', 'control',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('order_client', 'project_drawing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('order_client', 'measurements',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
