"""empty message

Revision ID: f1303235051a
Revises: 1ef6b2321964
Create Date: 2023-03-08 14:53:07.479800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1303235051a'
down_revision = '1ef6b2321964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_work_slabs', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_work_part', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_user', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status_pause', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pause_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('status_start',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('status_end',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_constraint('fk_performance_work_connection_work_part_part_works', type_='foreignkey')
        batch_op.drop_constraint('fk_performance_work_connection_user_user', type_='foreignkey')
        batch_op.drop_constraint('fk_performance_work_connection_work_slabs_slab_works', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_performance_work_id_work_slabs_slab_works'), 'slab_works', ['id_work_slabs'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_performance_work_id_work_part_part_works'), 'part_works', ['id_work_part'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_performance_work_id_user_user'), 'user', ['id_user'], ['id'])
        batch_op.drop_column('connection_work_part')
        batch_op.drop_column('connection_work_slabs')
        batch_op.drop_column('connection_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_user', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('connection_work_slabs', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('connection_work_part', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_performance_work_id_user_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_performance_work_id_work_part_part_works'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_performance_work_id_work_slabs_slab_works'), type_='foreignkey')
        batch_op.create_foreign_key('fk_performance_work_connection_work_slabs_slab_works', 'slab_works', ['connection_work_slabs'], ['id'])
        batch_op.create_foreign_key('fk_performance_work_connection_user_user', 'user', ['connection_user'], ['id'])
        batch_op.create_foreign_key('fk_performance_work_connection_work_part_part_works', 'part_works', ['connection_work_part'], ['id'])
        batch_op.alter_column('status_end',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('status_start',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('pause_date')
        batch_op.drop_column('status_pause')
        batch_op.drop_column('id_user')
        batch_op.drop_column('id_work_part')
        batch_op.drop_column('id_work_slabs')

    # ### end Alembic commands ###
