"""empty message

Revision ID: f4b808c0f345
Revises: 
Create Date: 2023-01-29 22:26:05.951467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b808c0f345'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('phone_number', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_phone_number'), ['phone_number'], unique=True)

    op.create_table('specialization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_departmet', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialization'))
    )
    with op.batch_alter_table('specialization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specialization_job_departmet'), ['job_departmet'], unique=False)
        batch_op.create_index(batch_op.f('ix_specialization_job_title'), ['job_title'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_title', sa.String(length=150), nullable=True),
    sa.Column('work_type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_works'))
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name=op.f('fk_followers_followed_id_user')),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name=op.f('fk_followers_follower_id_user'))
    )
    op.create_table('order_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_order', sa.String(length=300), nullable=True),
    sa.Column('title_stone', sa.String(length=300), nullable=True),
    sa.Column('object_description', sa.String(length=2000), nullable=True),
    sa.Column('address', sa.String(length=5000), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('measurements', sa.Boolean(), nullable=False),
    sa.Column('project_drawing', sa.Boolean(), nullable=False),
    sa.Column('control', sa.Boolean(), nullable=False),
    sa.Column('clients_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clients_id'], ['clients.id'], name=op.f('fk_order_client_clients_id_clients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_client'))
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_post_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post'))
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)

    op.create_table('part_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_part', sa.String(length=16), nullable=True),
    sa.Column('thickness', sa.String(length=150), nullable=True),
    sa.Column('value', sa.String(length=150), nullable=True),
    sa.Column('deadline_part', sa.DateTime(), nullable=True),
    sa.Column('oreder_of_client', sa.Integer(), nullable=False),
    sa.Column('part_works', sa.Integer(), nullable=False),
    sa.Column('set_worker', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oreder_of_client'], ['order_client.id'], name=op.f('fk_part_works_oreder_of_client_order_client')),
    sa.ForeignKeyConstraint(['part_works'], ['works.id'], name=op.f('fk_part_works_part_works_works')),
    sa.ForeignKeyConstraint(['set_worker'], ['user.id'], name=op.f('fk_part_works_set_worker_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_part_works'))
    )
    with op.batch_alter_table('part_works', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_part_works_number_part'), ['number_part'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_works_thickness'), ['thickness'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_works_value'), ['value'], unique=False)

    op.create_table('pre_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_order_client', sa.Integer(), nullable=False),
    sa.Column('work_type', sa.Integer(), nullable=False),
    sa.Column('set_worker', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['number_order_client'], ['order_client.id'], name=op.f('fk_pre_product_number_order_client_order_client')),
    sa.ForeignKeyConstraint(['set_worker'], ['user.id'], name=op.f('fk_pre_product_set_worker_user')),
    sa.ForeignKeyConstraint(['work_type'], ['works.id'], name=op.f('fk_pre_product_work_type_works')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pre_product'))
    )
    op.create_table('slab_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_slab', sa.String(length=16), nullable=True),
    sa.Column('thickness', sa.String(length=150), nullable=True),
    sa.Column('value', sa.String(length=150), nullable=True),
    sa.Column('oreder_of_client', sa.Integer(), nullable=False),
    sa.Column('slab_works', sa.Integer(), nullable=False),
    sa.Column('set_worker', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oreder_of_client'], ['order_client.id'], name=op.f('fk_slab_works_oreder_of_client_order_client')),
    sa.ForeignKeyConstraint(['set_worker'], ['user.id'], name=op.f('fk_slab_works_set_worker_user')),
    sa.ForeignKeyConstraint(['slab_works'], ['works.id'], name=op.f('fk_slab_works_slab_works_works')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slab_works'))
    )
    with op.batch_alter_table('slab_works', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slab_works_number_slab'), ['number_slab'], unique=False)
        batch_op.create_index(batch_op.f('ix_slab_works_thickness'), ['thickness'], unique=False)
        batch_op.create_index(batch_op.f('ix_slab_works_value'), ['value'], unique=False)

    op.create_table('performance_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_work_slabs', sa.Integer(), nullable=False),
    sa.Column('connection_work_part', sa.Integer(), nullable=False),
    sa.Column('connection_user', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status_start', sa.Boolean(), nullable=False),
    sa.Column('status_end', sa.Boolean(), nullable=False),
    sa.Column('lead_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connection_user'], ['user.id'], name=op.f('fk_performance_work_connection_user_user')),
    sa.ForeignKeyConstraint(['connection_work_part'], ['part_works.id'], name=op.f('fk_performance_work_connection_work_part_part_works')),
    sa.ForeignKeyConstraint(['connection_work_slabs'], ['slab_works.id'], name=op.f('fk_performance_work_connection_work_slabs_slab_works')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_work'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_work')
    with op.batch_alter_table('slab_works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slab_works_value'))
        batch_op.drop_index(batch_op.f('ix_slab_works_thickness'))
        batch_op.drop_index(batch_op.f('ix_slab_works_number_slab'))

    op.drop_table('slab_works')
    op.drop_table('pre_product')
    with op.batch_alter_table('part_works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_works_value'))
        batch_op.drop_index(batch_op.f('ix_part_works_thickness'))
        batch_op.drop_index(batch_op.f('ix_part_works_number_part'))

    op.drop_table('part_works')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))

    op.drop_table('post')
    op.drop_table('order_client')
    op.drop_table('followers')
    op.drop_table('works')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.drop_index(batch_op.f('ix_user_last_name'))
        batch_op.drop_index(batch_op.f('ix_user_first_name'))

    op.drop_table('user')
    with op.batch_alter_table('specialization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specialization_job_title'))
        batch_op.drop_index(batch_op.f('ix_specialization_job_departmet'))

    op.drop_table('specialization')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_phone_number'))
        batch_op.drop_index(batch_op.f('ix_clients_last_name'))
        batch_op.drop_index(batch_op.f('ix_clients_first_name'))

    op.drop_table('clients')
    # ### end Alembic commands ###
