"""empty message

Revision ID: fb0b31a551b9
Revises: ef640376319a
Create Date: 2022-12-19 13:24:14.538610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0b31a551b9'
down_revision = 'ef640376319a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_specialization_job_departmet', table_name='specialization')
    op.drop_column('specialization', 'job_departmet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialization', sa.Column('job_departmet', sa.VARCHAR(length=200), nullable=True))
    op.create_index('ix_specialization_job_departmet', 'specialization', ['job_departmet'], unique=False)
    # ### end Alembic commands ###
